### ISSUE TITLE
Code lists for commodities

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/rp-org-frontend#15]
Code list for commodities is located both in the (often hidden) codeslist tabs of google spreadsheet and on PoolParty (requires login)
https://docs.google.com/spreadsheets/d/16vuQCT92gYsMGGNGgX-j12-giCmO3SrUak6cG8oulMM/edit#gid=1609374283
Fine to only display the ones that already have value

and originates from annex 3 of this document:
http://www-wds.worldbank.org/external/default/WDSContentServer/WDSP/CTR/2016/02/25/090224b0841b02d1/2_0/Rendered/PDF/Options0for0Ex00better0and0the0best.pdf

Fine to validate list in spreadsheet and then only display those that have already a value in loaded database.

**Comment by davidmihalyi** [comment]
Also note that list might need further small fine tuning in future

**Comment by byndcivilization** [comment]
Pool party wont really work to replace the actual commodity collection. I do hope that we can use it in place of the alias model we are currently rolling.

Ive got the stuff from the spreadsheet in there now. Names are strings and theres an id filed that is '-' instead of spaces. We can use this for routing. so the aluminium commodity page would be http://resourceprojects.org/commodity/aluminum.

**Comment by davidmihalyi** [comment]
that works well!

**Comment by byndcivilization** [comment]
These are all loaded. moved routing to #16

**Comment by byndcivilization** [comment]
pool party to #17
